### ISSUE TITLE
Pow + i18n

### ISSUE THREAD

**Issue by anzaika** [danschultzer/pow#299]
This seems like a copy of #106 but still I can't figure this one out.

With this setup:
```
# /lib/app_web/router.ex

use Pow.Phoenix.Router
use Pow.Extension.Phoenix.Router, otp_app: :app_web

pipeline :protected do
  plug(Pow.Plug.RequireAuthenticated,
  error_handler: Pow.Phoenix.PlugErrorHandler)
end

scope "/:locale" do                                                          
  pipe_through([:browser])                                                  
  pow_routes()                                                               
  pow_extension_routes()                                                     
end            
```
And a plug in the browser pipeline that basically just assigns the correct locale from the url params.

When browsing to  `/en/session/new` I get this error:

```
protocol Phoenix.Param not implemented for [] of type List.
This protocol is implemented for the following type(s): Any, Map, Atom, BitString, Integer
```
Looks like I need to override the default Pow.Phoenix.SessionController action just can't figure out how. Could you, please, give me some ideas?

Thanks in advance!

**Comment by danschultzer** [comment]
Can you post the full stack trace? I'm not sure where the error originates from.

**Comment by anzaika** [comment]
Sure! Jess - is the app name.

```
Server: localhost:4000 (http)
Request: GET /en/session/new
** (exit) an exception was raised:
    ** (Protocol.UndefinedError) protocol Phoenix.Param not implemented for [] of type List. This protocol is implemented for the following type(s): Any, Map, Atom, BitString, Integer
        (phoenix) lib/phoenix/param.ex:121: Phoenix.Param.Any.to_param/1
        (jess) Jess.Router.Helpers.pow_session_path/4
        (pow) lib/pow/phoenix/controllers/session_controller.ex:71: Pow.Phoenix.SessionController.assign_create_path/2
        (pow) lib/pow/phoenix/controllers/session_controller.ex:1: Pow.Phoenix.SessionController.phoenix_controller_pipeline/2
        (phoenix) lib/phoenix/router.ex:288: Phoenix.Router.__call__/2
        (jess) lib/jess/endpoint.ex:1: Jess.Endpoint.plug_builder_call/2
        (jess) lib/plug/debugger.ex:122: Jess.Endpoint."call (overridable 3)"/2
        (jess) lib/jess/endpoint.ex:1: Jess.Endpoint."call (overridable 4)"/2
        (jess) lib/jess/endpoint.ex:1: Jess.Endpoint.call/2
        (phoenix) lib/phoenix/endpoint/cowboy2_handler.ex:42: Phoenix.Endpoint.Cowboy2Handler.init/4
        (cowboy) /home/anzaika/projects/weexpi/deps/cowboy/src/cowboy_handler.erl:41: :cowboy_handler.execute/2
        (cowboy) /home/anzaika/projects/weexpi/deps/cowboy/src/cowboy_stream_h.erl:296: :cowboy_stream_h.execute/3
        (cowboy) /home/anzaika/projects/weexpi/deps/cowboy/src/cowboy_stream_h.erl:274: :cowboy_stream_h.request_process/3
        (stdlib) proc_lib.erl:249: :proc_lib.init_p_do_apply/3
```

**Comment by danschultzer** [comment]
Ok, I see the issue is now. You will either need to add templates (as the dev did in #106) and set the create action manually, or add custom routes. It's because the session path generator call will be `session_path(@conn, :create, query_params ...)` instead of the required `session_path(@conn, :create, locale, query_params ...)`.

If you add [custom routes](https://github.com/danschultzer/pow#callback-routes), then you can [override](https://hexdocs.pm/pow/Pow.Phoenix.Routes.html#module-usage) the session route path generator like so:

```elixir
defmodule MyAppWeb.Pow.Routes do
  use Pow.Phoenix.Routes
  alias MyAppWeb.Router.Helpers, as: Routes

  @impl true
  def session_path(conn, verb, query_params) do
    session_path(conn, verb, Map.get(conn.params, :locale, "en") query_params)
  end
end
```

But it's probably better to override all routes:

```elixir
defmodule MyAppWeb.Pow.Routes do
  use Pow.Phoenix.Routes
  alias MyAppWeb.Router.Helpers, as: Routes

  @impl true
  def url_for(conn, plug, verb, vars, query_params) do
    vars = [Map.get(conn.params, :locale, "en")] ++ vars

    Pow.Phoenix.Routes.url_for(conn, plug, verb, vars, query_params)
  end
end
```

However, I'm thinking that maybe the [path gen calls](https://github.com/danschultzer/pow/blob/v1.0.13/lib/pow/phoenix/controllers/session_controller.ex#L74-L79) in the Pow Phoenix controllers should pass on the current path params so all of this isn't necessary. I think it's a fair assumption that the path params would be the same as currently used. I'll see if it can work and open a PR.

**Comment by anzaika** [comment]
Thanks a lot for the quick response! It didn't work the first time though, but that's OK =)

Just to provide an immediate solution to anyone who might be passing by this issue:
```
# /lib/my_app_web/pow_routes.ex
defmodule MyAppWeb.Pow.Routes do
  use Pow.Phoenix.Routes

  @impl true
  def path_for(conn, plug, verb, vars, query_params) do                                                                                                        
    vars = [Map.get(conn.params, :locale, "en")] ++ vars

    Pow.Phoenix.Routes.url_for(conn, plug, verb, vars, query_params)
  end
end

# /config/config.exs

config :my_app_web, :pow,
  routes_backend: MyAppWeb.Pow.Routes
```
@danschultzer Thanks a lot for your help and all the work you poured into this beautiful library.

**Comment by danschultzer** [comment]
Oh right it has to be path_for and url_for, updated the example thanks 😄

**Comment by danschultzer** [comment]
Also, I experimented a bit to see if I could easily pass on the path params, but couldn't find a way. The path params are converted into a map, which can't easily be converted back to the argument list required for the path helpers:

```elixir
%Plug.Conn{
  adapter: {Plug.Adapters.Test.Conn, :...},
  assigns: %{current_user: nil},
  before_send: [#Function<0.70535915/1 in Plug.CSRFProtection.call/2>,
   #Function<2.3059571/1 in Phoenix.Controller.fetch_flash/2>,
   #Function<0.35161479/1 in Plug.Session.before_send/2>,
   #Function<1.16531471/1 in Plug.Logger.call/2>],
  body_params: %{},
  cookies: %{},
  halted: false,
  host: "www.example.com",
  method: "GET",
  owner: #PID<0.449.0>,
  params: %{"locale" => "en"},
  path_info: ["en", "registration", "new"],
  path_params: %{"locale" => "en"},
  port: 80,
  private: %{
    Pow.Test.Phoenix.Router => {[], %{}},
    :phoenix_action => :new,
    :phoenix_controller => Pow.Phoenix.RegistrationController,
    :phoenix_endpoint => Pow.Test.Phoenix.Endpoint,
    :phoenix_flash => %{},
    :phoenix_format => "html",
    :phoenix_layout => {Pow.Test.Phoenix.LayoutView, :app},
    :phoenix_recycled => true,
    :phoenix_router => Pow.Test.Phoenix.Router,
    :phoenix_view => Pow.Phoenix.RegistrationView,
    :plug_session => %{},
    :plug_session_fetch => :done,
    :plug_skip_csrf_protection => true,
    :pow_config => [
      mod: Pow.Plug.Session,
      plug: Pow.Plug.Session,
      current_user_assigns_key: :current_user,
      session_key: "auth",
      cache_store_backend: Pow.Test.EtsCacheMock,
      messages_backend: Pow.Test.Phoenix.Messages,
      routes_backend: Pow.Test.Phoenix.Routes,
      user: Pow.Test.Ecto.Users.User,
      users_context: Pow.Test.ContextMock
    ]
  },
  query_params: %{},
  query_string: "",
  remote_ip: {127, 0, 0, 1},
  req_cookies: %{},
  req_headers: [],
  request_path: "/en/registration/new",
  resp_body: nil,
  resp_cookies: %{},
  resp_headers: [
    {"cache-control", "max-age=0, private, must-revalidate"},
    {"x-request-id", "Fc0FVY6l0dBRxdgAAAgh"},
    {"x-frame-options", "SAMEORIGIN"},
    {"x-xss-protection", "1; mode=block"},
    {"x-content-type-options", "nosniff"},
    {"x-download-options", "noopen"},
    {"x-permitted-cross-domain-policies", "none"},
    {"cross-origin-window-policy", "deny"}
  ],
  scheme: :http,
  script_name: [],
  secret_key_base: :...,
  state: :unset,
  status: nil
}
```

**Comment by sfusato** [comment]
I'm trying to marry Pow with [Alternate](https://github.com/boudra/alternate) (an i18n library for Phoenix) hoping this could provide a way to easily slap i18n over Pow.

So, when running `mix phx.routes`, instead of only the action (say `:create`), now I have a data structure like this `[action: :create, locale: "en"]`

`/register` is localised below and `/login` isn't for comparison
```
pow_registration_path  GET /register Pow.Phoenix.RegistrationController [action: :new, locale: "en"]
pow_registration_path  GET /it/iscriviti Pow.Phoenix.RegistrationController [action: :new, locale: "it"]
pow_session_path  GET /login Pow.Phoenix.SessionController :new
```
Where do I need to look further? Macro still feels like magic to me.

Right now I get:
```
FunctionClauseError at GET /register
no function clause matching in Pow.Phoenix.RegistrationController.call/2

Called with 2 arguments
%Plug.Conn{adapter: {Plug.Cowboy.Conn, :...} ....}
[action: :new, locale: "en"]
```

**Comment by danschultzer** [comment]
It's because alternate requires you to use a custom controller macro: https://github.com/boudra/alternate#controller

It really just should be a param, doesn't make any sense to do it that way. I highly recommend [cldr](https://github.com/elixir-cldr/cldr) for i18n. It has a plug to deal with locale so it can automatically pull from accept language as well: https://hexdocs.pm/ex_cldr/Cldr.Plug.SetLocale.html

Then you could just define the route like this:

```elixir
  scope "/:locale" do
    pow_routes()
  end
```

And pull it via the `:path` option.
