### ISSUE TITLE
Reset password issue in production using Bamboo

### ISSUE THREAD

**Issue by joepstender** [danschultzer/pow#312]
Locally resetting the password works fine, but when pushing live I get these errors. 
```
GET /reset-password/new
Sent 200 in 1ms
POST /reset-password
Sent 500 in 29ms
Converted error Bamboo.ApiError to 500 response
[error] #PID<0.3335.0> running MyAppWeb.Endpoint (connection #PID<0.3330.0>, stream id 4) terminated
  Server: myapp.onrender.com:80 (http)
  Request: POST /reset-password
  ** (exit) an exception was raised:
      ** (Bamboo.ApiError) {:option, :server_only, :honor_cipher_order}
          (bamboo) lib/bamboo/api_error.ex:42: Bamboo.ApiError.raise_api_error/1
          (bamboo) lib/bamboo/mailer.ex:145: Bamboo.Mailer.deliver_now/4
          (pow) lib/extensions/reset_password/phoenix/controllers/reset_password_controller.ex:33: PowResetPassword.Phoenix.ResetPasswordController.respond_create/1
          (pow) lib/extensions/reset_password/phoenix/controllers/reset_password_controller.ex:1: PowResetPassword.Phoenix.ResetPasswordController.action/2
          (pow) lib/extensions/reset_password/phoenix/controllers/reset_password_controller.ex:1: PowResetPassword.Phoenix.ResetPasswordController.phoenix_controller_pipeline/2
          (phoenix) lib/phoenix/router.ex:288: Phoenix.Router.__call__/2
          (myapp) lib/myapp_web/endpoint.ex:1: MyAppWeb.Endpoint.plug_builder_call/2
          (myapp) lib/myapp_web/endpoint.ex:1: MyAppWeb.Endpoint.call/2
```
I can't figure out if this is a configuration issue (checked them twice), a Bamboo issue, or a Pow issue.

**Comment by danschultzer** [comment]
It's a Bamboo issue, due to hackney: https://github.com/benoitc/hackney/issues/591

Update hackney to `>= 1.15.2` and it will work again.

**Comment by joepstender** [comment]
I'm sure I googled "(Bamboo.ApiError) {:option, :server_only, :honor_cipher_order}" but I didn't see the link to that issue... Spooky.
