### ISSUE TITLE
No function clause matching in CredentialsCache.put (line 70) 

### ISSUE THREAD

**Issue by lilayoung** [danschultzer/pow#339]
Hi, following the instructions from the API guide, I run into this error. The crucial part seems to be the third parameter {user, metadata}. The user details were saved into the database. 
Am new to Elixir, would appreciate any help in understanding how to fix this.. thank you! 

**Function call:** 
$ curl -X POST -d "user[email]=test@example.com&user[password]=secret1234" http://localhost:4000/api/v1/session
{"data":{"renew_token":"RENEW_TOKEN","token":"AUTH_TOKEN"}}

**Logs:**
From the webpage log: 
```
Attempted function clauses (showing 1 out of 1)
def put(config, session_id, {user, metadata})

Params
user
%{"confirm_password" => "secret1234", "email" => "test@example.com", "password" => "secret1234"}
```

```
[error] #PID<0.490.0> running CashewWeb.Endpoint (connection #PID<0.489.0>, stream id 1) terminated
Server: localhost:4000 (http)
Request: POST /api/v1/registration
** (exit) an exception was raised:
    ** (FunctionClauseError) no function clause matching in Pow.Store.CredentialsCache.put/3
        (pow) lib/pow/store/credentials_cache.ex:70: 

        Pow.Store.CredentialsCache.put(
       1 [backend: Pow.Store.Backend.EtsCache], 
       2 "5b5cebf1-a667-4f92-9a01-3b08cae8174e", 
       3 %Cashew.Users.User{__meta__: #Ecto.Schema.Metadata<:loaded, "users">, 
        confirm_password: nil, 
        current_password: nil, 
        email: "test@example.com", 
        id: 2, inserted_at: ~N[2019-11-25 18:55:39], 
        password: nil, password_hash: "$pbkdf2-sha512$100000$4cXRADsA613UDCUQHtEy/w==$1qj5QgmuMynv/qrw0lgJj56NMUqiVnJagfuNm3bYkY6RlicEyKZ0EfO/SUZNc+6yGVjrXmr1NEGe2ui6ypfd6Q==", 
        updated_at: ~N[2019-11-25 18:55:39]}        )


        (cashew) lib/cashew_web/api_auth_plug.ex:35: CashewWeb.APIAuthPlug.create/3
        (cashew) lib/cashew_web/api_auth_plug.ex:3: CashewWeb.APIAuthPlug.do_create/3
        (pow) lib/pow/plug.ex:174: Pow.Plug.maybe_create_auth/3
        (cashew) lib/cashew_web/controllers/api/v1/registration_controller.ex:11: CashewWeb.API.V1.RegistrationController.create/2
        (cashew) lib/cashew_web/controllers/api/v1/registration_controller.ex:1: CashewWeb.API.V1.RegistrationController.action/2
        (cashew) lib/cashew_web/controllers/api/v1/registration_controller.ex:1: CashewWeb.API.V1.RegistrationController.phoenix_controller_pipeline/2
        (phoenix) lib/phoenix/router.ex:288: Phoenix.Router.__call__/2
        (cashew) lib/cashew_web/endpoint.ex:1: CashewWeb.Endpoint.plug_builder_call/2
        (cashew) lib/plug/debugger.ex:122: CashewWeb.Endpoint."call (overridable 3)"/2
        (cashew) lib/cashew_web/endpoint.ex:1: CashewWeb.Endpoint.call/2
        (phoenix) lib/phoenix/endpoint/cowboy2_handler.ex:42: Phoenix.Endpoint.Cowboy2Handler.init/4
        (cowboy) /Users/user/Desktop/Nov_2019_repos/elixir_learning/sweetie/deps/cowboy/src/cowboy_handler.erl:41: :cowboy_handler.execute/2
        (cowboy) /Users/user/Desktop/Nov_2019_repos/elixir_learning/sweetie/deps/cowboy/src/cowboy_stream_h.erl:320: :cowboy_stream_h.execute/3
        (cowboy) /Users/user/Desktop/Nov_2019_repos/elixir_learning/sweetie/deps/cowboy/src/cowboy_stream_h.erl:302: :cowboy_stream_h.request_process/3
        (stdlib) proc_lib.erl:249: :proc_lib.init_p_do_apply/3
 ```

**Comment by danschultzer** [comment]
It looks like you have followed an older guide. The store has changed since v1.0.14. The guide was updated in #317, and can be found here: https://hexdocs.pm/pow/1.0.15/api.html#content

**Comment by lilayoung** [comment]
Thank you. It is fixed. I compared the code and it seems like this is the relevant part: 
lib/my_app_web/api_auth_plug.ex
```
    CredentialsCache.put(store_config, token, {user, []})
    PersistentSessionCache.put(store_config, renew_token, {[id: user.id], []})
```
Is there anything else I should note?

**Comment by danschultzer** [comment]
Yeah make sure you got all changes: https://github.com/danschultzer/pow/pull/317/files

**Comment by lilayoung** [comment]
Thanks!
