### ISSUE TITLE
nil user_id causes app failure

### ISSUE THREAD

**Issue by dfalling** [danschultzer/pow#358]
I have a test to ensure that a nil email in an update will result in a changeset error.  I'm using `pow_user_id_field_changeset(attrs)`, which results in:
```
** (FunctionClauseError) no function clause matching in String.Break.trim_leading/1

     The following arguments were given to String.Break.trim_leading/1:

         # 1
         nil

     Attempted function clauses (showing 1 out of 1):

         def trim_leading(string) when is_binary(string)
...

stacktrace:
       (elixir) lib/elixir/unicode/properties.ex:288: String.Break.trim_leading/1
       (elixir) lib/string.ex:1108: String.trim/1
       (pow) lib/pow/ecto/schema.ex:307: Pow.Ecto.Schema.normalize_user_id_field_value/1
       (ecto) lib/ecto/changeset.ex:1133: Ecto.Changeset.update_change/3
       (pow) lib/pow/ecto/schema/changeset.ex:48: Pow.Ecto.Schema.Changeset.user_id_field_changeset/3
```

Is there a way to use the `pow_user_id_field_changeset` and receive changeset errors vs. this application error?

**Comment by dfalling** [comment]
My test:

```elixir
  @invalid_attrs %{email: nil, password: "password"}
...
    test "create_user/1 with invalid data returns error changeset" do
      assert {:error, %Ecto.Changeset{}} = Accounts.create_user(@invalid_attrs)
    end
```

My Context:
```elixir
  def create_user(attrs) do
    %User{}
    |> User.changeset(attrs)
    |> Repo.insert()
  end
```

My User:
```elixir
  def changeset(user_or_changeset, attrs) do
    user_or_changeset
    |> pow_user_id_field_changeset(attrs)
    |> pow_current_password_changeset(attrs)
    |> new_password_changeset(attrs, @pow_config)
    |> pow_extension_changeset(attrs)
    |> Ecto.Changeset.delete_change(:password)
  end
```

**Comment by danschultzer** [comment]
Sorry, a bunch of things and the holidays crept up so didn't have time to look at this before now.

I figure out a way to trigger this. The user has to already have the email set in the struct:

```elixir
User.pow_user_id_field_changeset(%User{email: "test"}, %{email: nil})
```

I don't know why it blows up in your case though, since you call the changeset with an empty struct. Maybe a default value is set for the struct key? In any case, I'll open a PR to fix this.

**Comment by danschultzer** [comment]
#364 hopefully resolves this for you 😄

**Comment by dfalling** [comment]
Perfect, thank you!
