### ISSUE TITLE
Reset password tests fails if not run in isolation

### ISSUE THREAD

**Issue by dfalling** [danschultzer/pow#359]
My `reset_password_controller_test` works great if I run that suite in isolation.  But if I run my full test suite, this test consistently fails because of an invalid reset token.  I'm guessing this is a side effect of other tests also interacting with the GenServer?  Is there a better way I can test this behavior?

```elixir
    test "reset password succeeds for correct key", %{conn: conn} do
      user = insert(:user)

      {:ok, %{token: token, user: user}, conn} =
        conn
        |> Pow.Plug.put_config(Application.get_env(:ido_api, :pow))
        |> PowResetPassword.Plug.create_reset_token(%{"email" => user.email})

      valid_attrs = %{key: token, password: "^hEsdg*F899", confirm_password: "^hEsdg*F899"}

      conn = put(conn, Routes.password_reset_path(conn, :update), password_reset: valid_attrs)

      assert json_response(conn, 200)["info"]["detail"] =~ "password has been reset"

      conn =
        post(conn, Routes.session_path(conn, :create),
          session: %{email: user.email, password: "^hEsdg*F899"}
        )

      assert response(conn, 204)
    end
```

**Comment by danschultzer** [comment]
Yeah, a [mock ETS cache](https://github.com/danschultzer/pow/blob/v1.0.15/test/support/ets_cache_mock.ex) is used for tests in Pow to isolate the tests, and keep the write synchronous. It may just be that the GenServer is too slow to update before you test the full suite, so you would need to use `:timer.sleep/1` after creating the reset token.

I wrote a little about synchronous ETS cache mock in https://github.com/danschultzer/pow/issues/311#issuecomment-546151186. You can initiate this mock in your tests:

```elixir
    test "reset password succeeds for correct key", %{conn: conn} do
      MyAppWeb.EtsCacheMock.init()
      pow_config = [otp_app: :ido_api, cache_store_backend: MyAppWeb.EtsCacheMock]

      user = insert(:user)

      {:ok, %{token: token, user: user}, conn} =
        conn
        |> Pow.Plug.put_config(pow_config)
        |> PowResetPassword.Plug.create_reset_token(%{"email" => user.email})

      valid_attrs = %{key: token, password: "^hEsdg*F899", confirm_password: "^hEsdg*F899"}

      conn = put(conn, Routes.password_reset_path(conn, :update), password_reset: valid_attrs)

      assert json_response(conn, 200)["info"]["detail"] =~ "password has been reset"

      conn =
        post(conn, Routes.session_path(conn, :create),
          session: %{email: user.email, password: "^hEsdg*F899"}
        )

      assert response(conn, 204)
    end
```

If you use the cache backend numerous places around your code, then you can also set it up in [the ConnCase](https://github.com/danschultzer/pow/blob/v1.0.15/test/support/phoenix/conn_case.ex):

```elixir
defmodule MyAppWeb.ConnCase do
  use ExUnit.CaseTemplate

  alias MyAppWeb.EtsCacheMock

  using do
    quote do
       # Import conveniences for testing with connections
      use Phoenix.ConnTest
      alias MyAppWeb.Router.Helpers, as: Routes

      # The default endpoint for testing
      @endpoint Endpoint
    end
  end

  setup _tags do
    EtsCacheMock.init()

    {:ok, conn: Phoenix.ConnTest.build_conn(), ets: EtsCacheMock}
  end
end
```

**Comment by dfalling** [comment]
Ah, thanks- I had trouble finding examples of how you were doing the testing.

I'm still somehow screwing this up though.  I've noticed that after my `conn = put(...` call, the `cache_store_backend` is no longer set in my conn.  I'm guessing I'm not using config correctly and it's getting overridden?

Here's my `password_reset_controller`:

```elixir
  def update(conn, %{
        "password_reset" => %{
          "key" => token,
          "password" => password,
          "confirm_password" => confirm_password
        }
      }) do
    case Plug.user_from_token(conn, token) do
      nil ->
        conn
        |> put_status(422)
        |> json(%{error: %{status: 422, message: "Invalid reset token"}})

      user ->
        update_user(conn, user, password, confirm_password)
    end
  end

  defp update_user(conn, user, password, confirm_password) do
    conn = conn |> Plug.assign_reset_password_user(user)

    case Plug.update_user_password(conn, %{
           "password" => password,
           "confirm_password" => confirm_password
         }) do
      {:ok, user, conn} ->
        config = Pow.Plug.fetch_config(conn)
        plug = Pow.Plug.get_plug(config)

        conn
        |> put_view(IdoApiWeb.PasswordResetView)
        |> plug.do_create(user, config)
        |> render("info.json", %{info: "Your password has been reset"})

      {:error, changeset, conn} ->
        conn
        |> put_status(:unprocessable_entity)
        |> put_view(IdoAppWeb.ChangesetView)
        |> render("error.json", changeset: changeset)
    end
  end
```

**Comment by danschultzer** [comment]
Oh right, you need to override the `:cache_store_backend` config setting in `config/test.exs`:

```elixir
config :ido_api, :pow, cache_backend: cache_store_backend: MyAppWeb.EtsCacheMock
```

This way it'll always use the `MyAppWeb.EtsCacheMock` in your tests. I've updated the above comment example.

**Comment by dfalling** [comment]
Oh yeah, that makes sense.

Ok I feel really close.  Hopefully the last thing- I can't get that Ets Mock to work, something about `EtsCacheMock.put/2`.  Is there any other setup you have to do to use it?

```
** (ArgumentError) argument error
     code: |> PowResetPassword.Plug.create_reset_token(%{"email" => user.email})
     stacktrace:
       (stdlib) :ets.insert(IdoApiWeb.Test.EtsCacheMock, [{["reset_token", "58b56600-747f-40e2-887a-8d23af855d3a"], %IdoApi.Accounts.User{__meta__: #Ecto.Schema.Metadata<:loaded, "users">, confirm_password: nil, current_password: nil, email: "email-2@example.com", email_confirmation_token: nil, email_confirmed_at: ~U[2011-04-17 14:00:00Z], id: 17283, inserted_at: ~N[2019-12-18 18:39:08], password: nil, password_hash: "$pbkdf2-sha512$100000$GA1GgJ1aRiXVr9XFMQAuRg==$xd1dO0g1ACf+RNGVHFAwyhgxHOhjWXnzfxEuJhNb6e/IBulXkr3UQ2DxIfcKhNDIsnQghvR9hRPt3khssBBNzQ==", role: "user", trips: #Ecto.Association.NotLoaded<association :trips is not loaded>, unconfirmed_email: nil, updated_at: ~N[2019-12-18 18:39:08]}}])
       (ido_api) test/support/ets_cache_mock.ex:32: IdoApiWeb.Test.EtsCacheMock.put/2
       (pow) lib/extensions/reset_password/plug.ex:67: PowResetPassword.Plug.maybe_store_reset_token/4
```

Thanks for all the help!

**Comment by dfalling** [comment]
Scratch that!  I put it in a `setup_all` block for my tests, but it actually needs to run in a `setup` block instead for each test.  Thanks!

**Comment by dfalling** [comment]
Aaah, I spoke too soon.  So adding it to `setup` worked for that test suite, but I realized all my other suites were now failing because of swapping out the cache in my test config.  Adding the cache init in my conn_case will also work for a single test suite, but when I run all my tests I get a new argument error:

```
test/ido_api_web/controllers/user_controller_test.exs:33
     ** (ArgumentError) argument error
     stacktrace:
       (stdlib) :ets.new(IdoApiWeb.Test.EtsCacheMock, [:ordered_set, :protected, :named_table])
       (ido_api) test/support/ets_cache_mock.ex:5: IdoApiWeb.Test.EtsCacheMock.init/0
       (ido_api) test/support/conn_case.ex:55: IdoApiWeb.ConnCase.__ex_unit_setup_0/1
       (ido_api) test/support/conn_case.ex:1: IdoApiWeb.ConnCase.__ex_unit__/2
       test/ido_api_web/controllers/user_controller_test.exs:1: IdoApiWeb.UserControllerTest.__ex_unit__/2
```

Can these tests not run in parallel due to the ETS Mock?

**Comment by danschultzer** [comment]
Yeah, you can't run them in parallel with the `:async` tag since that would cause multiple ETS tab creations at the same time. You can start up a single ETS instance in the test helper instead of using `setup`:

```elixir
ExUnit.start()
Ecto.Adapters.SQL.Sandbox.mode(MyApp.Repo, :manual)
MyAppWeb.EtsCacheMock.init()
```

This obviously won't isolate the ETS table to each test though, but for the test you got it's fine since a random UUID is used for the rest password tests.

Also sorry for the late reply, holidays and other stuff caught up with me and I simply didn't have time to get back to this before now.

**Comment by dfalling** [comment]
No worries for the delay, I've been pretty busy with the holidays too.  I tried using the test_helper, but I run into the same issues as when I was using setup_all vs setup- an argument error on `:ets.insert`.

I did get it working by just adding a a short timer delay to the one test that actually depends on the ETS.  I can use this workaround if there's not another easy fix.
