### ISSUE TITLE
Mnesia :bad_type error 

### ISSUE THREAD

**Issue by jung-hunsoo** [danschultzer/pow#37]
Recently I changed the credential config from default ets to mnesia explained in the readme guide.

It has worked in dev, but error is popped out in prod. (Release made via `Distillery` and `:mnesia` is included in `:extra_applications`.

Any clue?

### console
```elixir
 9월 24 09:29:11 nohogu1 nohogu[4506]: Loading nohogu...
 9월 24 09:29:11 nohogu1 nohogu[4506]: Starting dependencies..
 9월 24 09:29:11 nohogu1 nohogu[4506]: Creating database if not exists...
 9월 24 09:29:11 nohogu1 nohogu[4506]: Running migrations...
 9월 24 09:29:12 nohogu1 nohogu[4506]: Success!
 9월 24 09:29:12 nohogu1 nohogu[4506]: 09:29:12.159 [info] Already up
 9월 24 09:29:14 nohogu1 nohogu[4506]: 09:29:14.948 [info] Running NohoguWeb.Endpoint with Cowboy using http://0.0.0.0:4000
 9월 24 09:29:14 nohogu1 nohogu[4506]: 09:29:14.994 [info] Application nohogu exited: Nohogu.Application.start(:normal, []) returned an error: shutdown: failed to start c
 9월 24 09:29:14 nohogu1 nohogu[4506]:     ** (EXIT) an exception was raised:
 9월 24 09:29:14 nohogu1 nohogu[4506]:         ** (CaseClauseError) no case clause matching: {:aborted, {:bad_type, Pow.Store.Backend.MnesiaCache, :disc_copies, :"nohogu@
 9월 24 09:29:14 nohogu1 nohogu[4506]:             (pow) lib/pow/store/backend/mnesia_cache.ex:144: Pow.Store.Backend.MnesiaCache.table_init/1
 9월 24 09:29:14 nohogu1 nohogu[4506]:             (pow) lib/pow/store/backend/mnesia_cache.ex:54: Pow.Store.Backend.MnesiaCache.init/1
 9월 24 09:29:14 nohogu1 nohogu[4506]:             (stdlib) gen_server.erl:374: :gen_server.init_it/2
 9월 24 09:29:14 nohogu1 nohogu[4506]:             (stdlib) gen_server.erl:342: :gen_server.init_it/6
 9월 24 09:29:14 nohogu1 nohogu[4506]:             (stdlib) proc_lib.erl:249: :proc_lib.init_p_do_apply/3
 9월 24 09:29:16 nohogu1 nohogu[4506]: {"Kernel pid terminated",application_controller,"{application_start_failure,nohogu,{{shutdown,{failed_to_start_child,'Elixir.Pow.St
 9월 24 09:29:16 nohogu1 nohogu[4506]: Kernel pid terminated (application_controller) ({application_start_failure,nohogu,{{shutdown,{failed_to_start_child,'Elixir.Pow.Sto
 9월 24 09:29:16 nohogu1 nohogu[4506]: [1B blob data]
 9월 24 09:29:16 nohogu1 nohogu[4506]: Crash dump is being written to: erl_crash.dump...done
```

### config.ex
```elixir
# Authentication
config :nohogu, :pow,
  user: Nohogu.Users.User,
  repo: Nohogu.Repo,
  web_module: NohoguWeb,
  web_mailer_module: NohoguWeb,
  mailer_backend: NohoguWeb.PowMailer,
	messages_backend: NohoguWeb.Pow.Messages,
	routes_backend: NohoguWeb.Pow.Routes,
	cache_store_backend: Pow.Store.Backend.MnesiaCache,
	session_store: {Pow.Store.CredentialsCache, ttl: :timer.minutes(60), namespace: "credentials"},
	session_ttl_renewal: :timer.minutes(30),
  extensions: [PowResetPassword, PowEmailConfirmation, PowPersistentSession],
  controller_callbacks: Pow.Extension.Phoenix.ControllerCallbacks
```

### endpoint
```elixir
  plug Plug.Session,
    store: :cookie,
    key: "_nohogu_key",
    signing_salt: "SOME_KEY"

  plug Pow.Plug.Session, otp_app: :nohogu
```

**Comment by danschultzer** [comment]
Distillery doesn't include the `:mnesia` app by default, so you'll have to explicitly state that it's an included application in your `mix.exs` for it to be built into your release:

```elixir
defmodule MyApp.Application do
  use Mix.Project

  # ...

  def application do
    [
      mod: {MyApp.Application, []},
      extra_applications: [:logger, :runtime_tools],
      included_applications: [:mnesia] # <--- Add to :included_applications
    ]
  end

  # ...
end
```

**Comment by danschultzer** [comment]
I'm not sure if it'll be picked up in `:extra_applications`.

**Comment by danschultzer** [comment]
Also, if you experienced a failed start of your app the first time you deployed, because mnesia wasn't available, then remove the initialized mnesia data files in production and restart with the fixed version. I've experienced that these initialized files can't be used if the whole app is halted.

**Comment by danschultzer** [comment]
FWIW, I had trouble get this running myself the first time around. This was a production app with a few hundred daily visitors. The mnesia errors are difficult to read, but ever since I got the mnesia files initialized properly it has been working 100% of the time.

**Comment by danschultzer** [comment]
@jung-hunsoo did you get this working?

**Comment by jung-hunsoo** [comment]
@danschultzer Oh sorry. I've been in other issues..

Yeap, it's working now. Both `dev` and `prod` works fine. Actually I don't know it's working properly. At least it showed no error.
