### ISSUE TITLE
cannot perform Ecto.Repo.get/2 because the given value is nil

### ISSUE THREAD

**Issue by nesimtunc** [danschultzer/pow#396]
Hi,

After register a new user from `http://localhost:4000/registration/new` (I can see the new created user in db) I get this error,. Before I change my default id to `uuid` it was okay. After change I reset db using `ecto`, re-setup the app. But it's still same. 

```
config :my_app, MyApp.Repo, migration_primary_key: [name: :id, type: :binary_id, autogenerate: true, read_after_writes: true, default: {:fragment, "gen_random_uuid()"}]
```
Stacktrace:

```
[error] #PID<0.586.0> running my_appWeb.Endpoint (connection #PID<0.585.0>, stream id 1) terminated
Server: localhost:4000 (http)
Request: POST /registration
** (exit) an exception was raised:
    ** (ArgumentError) cannot perform Ecto.Repo.get/2 because the given value is nil
        (ecto) lib/ecto/repo/queryable.ex:391: Ecto.Repo.Queryable.query_for_get/2
        (ecto) lib/ecto/repo/queryable.ex:66: Ecto.Repo.Queryable.get!/4
        (pow) lib/pow/ecto/context.ex:227: Pow.Ecto.Context.reload_after_write/2
        (pow) lib/pow/plug.ex:136: Pow.Plug.create_user/2
        (pow) lib/pow/phoenix/controllers/controller.ex:99: Pow.Phoenix.Controller.action/3
        (pow) lib/pow/phoenix/controllers/registration_controller.ex:1: Pow.Phoenix.RegistrationController.action/2
        (pow) lib/pow/phoenix/controllers/registration_controller.ex:1: Pow.Phoenix.RegistrationController.phoenix_controller_pipeline/2
        (phoenix) lib/phoenix/router.ex:288: Phoenix.Router.__call__/2
        (my_app) lib/my_app_web/endpoint.ex:1: my_appWeb.Endpoint.plug_builder_call/2
        (my_app) lib/plug/debugger.ex:122: my_appWeb.Endpoint."call (overridable 3)"/2
        (my_app) lib/my_app_web/endpoint.ex:1: my_appWeb.Endpoint.call/2
        (phoenix) lib/phoenix/endpoint/cowboy2_handler.ex:42: Phoenix.Endpoint.Cowboy2Handler.init/4
        (cowboy) /Users/myuser/Documents/Projects/MyApp/v2/my_app/deps/cowboy/src/cowboy_handler.erl:41: :cowboy_handler.execute/2
        (cowboy) /Users/myuser/Documents/Projects/MyApp/v2/my_app/deps/cowboy/src/cowboy_stream_h.erl:320: :cowboy_stream_h.execute/3
        (cowboy) /Users/myuser/Documents/Projects/MyApp/v2/my_app/deps/cowboy/src/cowboy_stream_h.erl:302: :cowboy_stream_h.request_process/3
        (stdlib) proc_lib.erl:249: :proc_lib.init_p_do_apply/3
```

Thank you!

**Comment by danschultzer** [comment]
I believe you have to set `:read_after_writes` in the schemas, e.g. `@primary_key {:id, :binary_id, read_after_writes: true}`. AFAIK `:migration_primary_key` will only help with the migrations.

See this example in the Ecto docs for how to set it on all schemas: https://hexdocs.pm/ecto/3.3.1/Ecto.Schema.html#module-schema-attributes

```elixir
# Define a module to be used as base
defmodule MyApp.Schema do
  defmacro __using__(_) do
    quote do
      use Ecto.Schema
      @primary_key {:id, :binary_id, autogenerate: true}
      @foreign_key_type :binary_id
    end
  end
end

# Now use MyApp.Schema to define new schemas
defmodule MyApp.Comment do
  use MyApp.Schema

  schema "comments" do
    belongs_to :post, MyApp.Post
  end
end
```

**Comment by nesimtunc** [comment]
Oh I see! It works now! Thank you!
