### ISSUE TITLE
(Postgrex.Error) ERROR 23503 (foreign_key_violation) update or delete on table "users" violates foreign key constraint "user_identities_user_id_fkey" on table "user_identities"

### ISSUE THREAD

**Issue by jagoanmamah** [danschultzer/pow#511]
hey I’m trying to use delete_all like the code below
```
def delete_users(queryable) do
    Ecto.Multi.new()
    |> Ecto.Multi.delete_all(:delete_all, queryable)
    |> Phoenixbasic.Repo.transaction()
  end
```
but I get an error like this
```
[error] #PID<0.1729.0> running PhoenixbasicWeb.Endpoint (connection #PID<0.1728.0>, stream id 1) terminated
Server: localhost:4000 (http)
Request: DELETE /deleteall
** (exit) an exception was raised:
    ** (Postgrex.Error) ERROR 23503 (foreign_key_violation) update or delete on table "users" violates foreign key constraint "user_identities_user_id_fkey" on table "user_identities"

    table: user_identities
    constraint: user_identities_user_id_fkey

Key (id)=(881343b0-b94e-45c9-80ad-5b092c38b6b3) is still referenced from table "user_identities".
        (ecto_sql 3.4.3) lib/ecto/adapters/sql.ex:593: Ecto.Adapters.SQL.raise_sql_call_error/1
        (ecto_sql 3.4.3) lib/ecto/adapters/sql.ex:526: Ecto.Adapters.SQL.execute/5
        (ecto 3.4.3) lib/ecto/multi.ex:606: Ecto.Multi.apply_operation/4
        (ecto 3.4.3) lib/ecto/multi.ex:585: Ecto.Multi.apply_operation/5
        (elixir 1.10.3) lib/enum.ex:2111: Enum."-reduce/3-lists^foldl/2-0-"/3
        (ecto 3.4.3) lib/ecto/multi.ex:569: anonymous fn/5 in Ecto.Multi.apply_operations/5
        (ecto_sql 3.4.3) lib/ecto/adapters/sql.ex:875: anonymous fn/3 in Ecto.Adapters.SQL.checkout_or_transaction/4
        (db_connection 2.2.2) lib/db_connection.ex:1427: DBConnection.run_transaction/4
        (ecto 3.4.3) lib/ecto/repo/transaction.ex:20: Ecto.Repo.Transaction.transaction/4
        (phoenixbasic 0.1.0) lib/phoenixbasic_web/controllers/user_controller.ex:50: PhoenixbasicWeb.UserController.deleteall/2
        (phoenixbasic 0.1.0) lib/phoenixbasic_web/controllers/user_controller.ex:1: PhoenixbasicWeb.UserController.action/2
        (phoenixbasic 0.1.0) lib/phoenixbasic_web/controllers/user_controller.ex:1: PhoenixbasicWeb.UserController.phoenix_controller_pipeline/2
        (phoenix 1.5.1) lib/phoenix/router.ex:352: Phoenix.Router.__call__/2
        (phoenixbasic 0.1.0) lib/phoenixbasic_web/endpoint.ex:1: PhoenixbasicWeb.Endpoint.plug_builder_call/2
        (phoenixbasic 0.1.0) lib/plug/debugger.ex:132: PhoenixbasicWeb.Endpoint."call (overridable 3)"/2
        (phoenixbasic 0.1.0) lib/phoenixbasic_web/endpoint.ex:1: PhoenixbasicWeb.Endpoint.call/2
        (phoenix 1.5.1) lib/phoenix/endpoint/cowboy2_handler.ex:64: Phoenix.Endpoint.Cowboy2Handler.init/4
        (cowboy 2.7.0) /home/wahyu/phoenixbasic/deps/cowboy/src/cowboy_handler.erl:41: :cowboy_handler.execute/2
        (cowboy 2.7.0) /home/wahyu/phoenixbasic/deps/cowboy/src/cowboy_stream_h.erl:320: :cowboy_stream_h.execute/3
        (cowboy 2.7.0) /home/wahyu/phoenixbasic/deps/cowboy/src/cowboy_stream_h.erl:302: :cowboy_stream_h.request_process/3
```

**Comment by danschultzer** [comment]
This is PowAssent issue. Got an issue tracked to resolve it: https://github.com/pow-auth/pow_assent/issues/168

If you update the migration to set the `on_delete: :delete_all` on the users reference, then this should be working.
