### ISSUE TITLE
Error generating extension templates

### ISSUE THREAD

**Issue by brightball** [danschultzer/pow#7]
I was going through the readme trying things out and got the following error when I ran the command to generate the extension templates.

```
$ mix pow.extension.phoenix.gen.templates --extension PowResetPassword --extension PowEmailConfirmation
warning: found quoted keyword "test" but the quotes are not required. Note that keywords are always atoms, even when quoted, and quotes should only be used to introduce keywords with foreign characters in them
  mix.exs:62

* creating lib/my_app_web/views/pow_reset_password/reset_password_view.ex
** (ArgumentError) argument error
    :erlang.binary_to_existing_atom("edit", :utf8)
    (elixir) lib/string.ex:2169: String.to_existing_atom/1
    (elixir) lib/enum.ex:1314: Enum."-map/2-lists^map/1-0-"/2
    (elixir) lib/enum.ex:1314: Enum."-map/2-lists^map/1-0-"/2
    lib/mix/pow/phoenix.ex:59: Mix.Pow.Phoenix.create_templates/4
    (elixir) lib/enum.ex:765: Enum."-each/2-lists^foreach/1-0-"/2
    (elixir) lib/enum.ex:765: Enum.each/2
    (elixir) lib/enum.ex:765: Enum."-each/2-lists^foreach/1-0-"/2
```

**Comment by danschultzer** [comment]
Update the `1.0.0-rc.2`, and it should work.

**Comment by brightball** [comment]
Fixed it. Thanks!

**Comment by danschultzer** [comment]
Thanks for trying out Pow! Any feedback will help me iron out the last details :)
