### ISSUE TITLE
Template generation broken

### ISSUE THREAD

**Issue by jpinnix** [danschultzer/pow#8]
Running `mix pow.phoenix.gen.templates` or `mix pow.phoenix.gen.templates --context-app Ss` gives the error:

```erlang
* creating lib/ss_web/views/pow/registration_view.ex
** (ArgumentError) argument error
    :erlang.binary_to_existing_atom("edit", :utf8)
    (elixir) lib/string.ex:2089: String.to_existing_atom/1
    (elixir) lib/enum.ex:1294: Enum."-map/2-lists^map/1-0-"/2
    (elixir) lib/enum.ex:1294: Enum."-map/2-lists^map/1-0-"/2
    lib/mix/pow/phoenix.ex:59: Mix.Pow.Phoenix.create_templates/4
    (elixir) lib/enum.ex:737: Enum."-each/2-lists^foreach/1-0-"/2
    (elixir) lib/enum.ex:737: Enum.each/2
    lib/mix/tasks/phoenix/pow.phoenix.gen.templates.ex:41: Mix.Tasks.Pow.Phoenix.Gen.Templates.create_template_files/1
```
It does generate `lib/ss_web/views/pow/registration_view.ex`, but that is all.

**Comment by danschultzer** [comment]
Updating to `v1.0.0-rc.3` should solve that.

**Comment by jpinnix** [comment]
Indeed it does. Thanks!
